// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line qtpl/index.qtpl:1
package main

//line qtpl/index.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line qtpl/index.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line qtpl/index.qtpl:2
func streamserve(qw422016 *qt422016.Writer, Posts []Post, Me User, CSRFToken string, Flash string) {
//line qtpl/index.qtpl:2
	qw422016.N().S(`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Iscogram</title>
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="isu-title">
          <h1><a href="/">Iscogram</a></h1>
        </div>
        <div class="isu-header-menu">
          `)
//line qtpl/index.qtpl:17
	if Me.ID == 0 {
//line qtpl/index.qtpl:17
		qw422016.N().S(`
          <div><a href="/login">ログイン</a></div>
          `)
//line qtpl/index.qtpl:19
	} else {
//line qtpl/index.qtpl:19
		qw422016.N().S(`
          <div><a href="/@`)
//line qtpl/index.qtpl:20
		qw422016.E().S(Me.AccountName)
//line qtpl/index.qtpl:20
		qw422016.N().S(`"><span class="isu-account-name">`)
//line qtpl/index.qtpl:20
		qw422016.E().S(Me.AccountName)
//line qtpl/index.qtpl:20
		qw422016.N().S(`</span>さん</a></div>
          `)
//line qtpl/index.qtpl:21
		if Me.Authority == 1 {
//line qtpl/index.qtpl:21
			qw422016.N().S(`
          <div><a href="/admin/banned">管理者用ページ</a></div>
          `)
//line qtpl/index.qtpl:23
		}
//line qtpl/index.qtpl:23
		qw422016.N().S(`
          <div><a href="/logout">ログアウト</a></div>
          `)
//line qtpl/index.qtpl:25
	}
//line qtpl/index.qtpl:25
	qw422016.N().S(`
        </div>
      </div>

      <div class="isu-submit">
        <form method="post" action="/" enctype="multipart/form-data">
          <div class="isu-form">
            <input type="file" name="file" value="file">
          </div>
          <div class="isu-form">
            <textarea name="body"></textarea>
          </div>
          <div class="form-submit">
            <input type="hidden" name="csrf_token" value="`)
//line qtpl/index.qtpl:38
	qw422016.E().S(CSRFToken)
//line qtpl/index.qtpl:38
	qw422016.N().S(`">
            <input type="submit" name="submit" value="submit">
          </div>
          <div id="notice-message" class="alert alert-danger">
            `)
//line qtpl/index.qtpl:42
	qw422016.E().S(Flash)
//line qtpl/index.qtpl:42
	qw422016.N().S(`
          </div>
        </form>
      </div>

      <div class="isu-posts">
        `)
//line qtpl/index.qtpl:48
	for _, post := range Posts {
//line qtpl/index.qtpl:48
		qw422016.N().S(`
        <div class="isu-post" id="pid_`)
//line qtpl/index.qtpl:49
		qw422016.N().D(post.ID)
//line qtpl/index.qtpl:49
		qw422016.N().S(`" data-created-at="`)
//line qtpl/index.qtpl:49
		qw422016.E().S(post.CreatedAt.Format("2006-01-02T15:04:05-07:00"))
//line qtpl/index.qtpl:49
		qw422016.N().S(`">
          <div class="isu-post-header">
            <a href="/@`)
//line qtpl/index.qtpl:51
		qw422016.E().S(post.User.AccountName)
//line qtpl/index.qtpl:51
		qw422016.N().S(` " class="isu-post-account-name">`)
//line qtpl/index.qtpl:51
		qw422016.E().S(post.User.AccountName)
//line qtpl/index.qtpl:51
		qw422016.N().S(`</a>
            <a href="/posts/`)
//line qtpl/index.qtpl:52
		qw422016.N().D(post.ID)
//line qtpl/index.qtpl:52
		qw422016.N().S(`" class="isu-post-permalink">
              <time class="timeago" datetime="`)
//line qtpl/index.qtpl:53
		qw422016.E().S(post.CreatedAt.Format("2006-01-02T15:04:05-07:00"))
//line qtpl/index.qtpl:53
		qw422016.N().S(`"></time>
            </a>
          </div>
          <div class="isu-post-image">
            <img src="`)
//line qtpl/index.qtpl:57
		qw422016.E().S(imageURL(post))
//line qtpl/index.qtpl:57
		qw422016.N().S(`" class="isu-image">
          </div>
          <div class="isu-post-text">
            <a href="/@`)
//line qtpl/index.qtpl:60
		qw422016.E().S(post.User.AccountName)
//line qtpl/index.qtpl:60
		qw422016.N().S(`" class="isu-post-account-name">`)
//line qtpl/index.qtpl:60
		qw422016.E().S(post.User.AccountName)
//line qtpl/index.qtpl:60
		qw422016.N().S(`</a>
            `)
//line qtpl/index.qtpl:61
		qw422016.E().S(post.Body)
//line qtpl/index.qtpl:61
		qw422016.N().S(`
          </div>
          <div class="isu-post-comment">
            <div class="isu-post-comment-count">
              comments: <b>`)
//line qtpl/index.qtpl:65
		qw422016.N().D(post.CommentCount)
//line qtpl/index.qtpl:65
		qw422016.N().S(`</b>
            </div>

            `)
//line qtpl/index.qtpl:68
		for _, comment := range post.Comments {
//line qtpl/index.qtpl:68
			qw422016.N().S(`
            <div class="isu-comment">
              <a href="/@`)
//line qtpl/index.qtpl:70
			qw422016.E().S(comment.User.AccountName)
//line qtpl/index.qtpl:70
			qw422016.N().S(`" class="isu-comment-account-name">`)
//line qtpl/index.qtpl:70
			qw422016.E().S(comment.User.AccountName)
//line qtpl/index.qtpl:70
			qw422016.N().S(`</a>
              <span class="isu-comment-text">`)
//line qtpl/index.qtpl:71
			qw422016.E().S(comment.Comment)
//line qtpl/index.qtpl:71
			qw422016.N().S(`</span>
            </div>
            `)
//line qtpl/index.qtpl:73
		}
//line qtpl/index.qtpl:73
		qw422016.N().S(`
            <div class="isu-comment-form">
              <form method="post" action="/comment">
                <input type="text" name="comment">
                <input type="hidden" name="post_id" value="`)
//line qtpl/index.qtpl:77
		qw422016.N().D(post.ID)
//line qtpl/index.qtpl:77
		qw422016.N().S(`">
                <input type="hidden" name="csrf_token" value="`)
//line qtpl/index.qtpl:78
		qw422016.E().S(CSRFToken)
//line qtpl/index.qtpl:78
		qw422016.N().S(`">
                <input type="submit" name="submit" value="submit">
              </form>
            </div>
          </div>
        </div>

        `)
//line qtpl/index.qtpl:85
	}
//line qtpl/index.qtpl:85
	qw422016.N().S(`
      </div>

      <div id="isu-post-more">
        <button id="isu-post-more-btn">もっと見る</button>
        <img class="isu-loading-icon" src="/img/ajax-loader.gif">
      </div>
    </div>
    <script src="/js/jquery-2.2.0.js"></script>
    <script src="/js/jquery.timeago.js"></script>
    <script src="/js/jquery.timeago.ja.js"></script>
    <script src="/js/main.js"></script>
  </body>
</html>
`)
//line qtpl/index.qtpl:99
}

//line qtpl/index.qtpl:99
func writeserve(qq422016 qtio422016.Writer, Posts []Post, Me User, CSRFToken string, Flash string) {
//line qtpl/index.qtpl:99
	qw422016 := qt422016.AcquireWriter(qq422016)
//line qtpl/index.qtpl:99
	streamserve(qw422016, Posts, Me, CSRFToken, Flash)
//line qtpl/index.qtpl:99
	qt422016.ReleaseWriter(qw422016)
//line qtpl/index.qtpl:99
}

//line qtpl/index.qtpl:99
func serve(Posts []Post, Me User, CSRFToken string, Flash string) string {
//line qtpl/index.qtpl:99
	qb422016 := qt422016.AcquireByteBuffer()
//line qtpl/index.qtpl:99
	writeserve(qb422016, Posts, Me, CSRFToken, Flash)
//line qtpl/index.qtpl:99
	qs422016 := string(qb422016.B)
//line qtpl/index.qtpl:99
	qt422016.ReleaseByteBuffer(qb422016)
//line qtpl/index.qtpl:99
	return qs422016
//line qtpl/index.qtpl:99
}
